<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

 


  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\HumanTouchP2_Enhancedv3\HumanTouchP2.Enhancedv3.csproj" />
    <ProjectReference Include="..\..\Libraries\QTP.Common\QTP.Common.csproj" />
  </ItemGroup>


</Project>
