<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="新建文本文档.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" Version="1.57.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\QTP.Common\QTP.Common.csproj" />
  </ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="if not exist &quot;../../Build/publish/Plugins&quot; mkdir &quot;../../Build/publish/Plugins&quot;" />
		<Exec Command="xcopy &quot;$(OutDir)$(ProjectName).dll&quot; &quot;../../Build/publish/Plugins&quot; /y" />
	</Target>

</Project>
