<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Plugins/SMAd/SMAd.csproj" />
    <Compile Include="../../MainClient/Services/SmAdExecutor.cs" Link="SmAdExecutor.cs" />
  </ItemGroup>
</Project>
